
FROM docker-coastal-source

USER root

RUN apt-get update
RUN apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils git make wget build-essential vim python3-pip

RUN pip install --upgrade pip

USER root

ADD docker/requirements.txt .
RUN pip install -r requirements.txt

#RUN mkdir /opt/conda/lib/python3.10/site-packages/SOURCE
ADD SOURCE /opt/conda/lib/python3.10/site-packages/SOURCE

USER jovyan



