# update if change version
ARG PYTHON_VERSION="3.12"
# update if you prefer a different distribution
#ARG LINUX_DIST="slim-bookworm"
ARG LINUX_DIST="alpine"

FROM python:${PYTHON_VERSION}-${LINUX_DIST}
ARG PYTHON_VERSION

WORKDIR /usr/src/app 


# debian / ubuntu
#RUN apt-get update
#RUN apt-get upgrade -y

##RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils git make wget build-essential vim python3-pip
#RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils wget vim 
#RUN apt-get clean all


# alpine
RUN apk update
RUN apk upgrade

#RUN apk add wget vim py3-pip proj proj-util proj-dev build-base py3-pyproject-api geos-dev
RUN apk add wget vim nano proj proj-util proj-dev build-base py3-pyproject-api geos-dev hdf5-dev netcdf-dev gdal-dev


##USER python
#RUN export PROJ_DIR=/usr/local
#RUN export PROJ_DIR=/usr/share/proj

RUN pip install --upgrade pip

ADD docker/requirements.txt /usr/src/app
RUN pip3 install -r requirements.txt

RUN mkdir /usr/local/lib/python${PYTHON_VERSION}/site-packages/SOURCE
ADD SOURCE /usr/local/lib/python${PYTHON_VERSION}/site-packages/SOURCE

# alpine
#RUN apk del proj-dev build-base geos-dev hdf5-dev netcdf-dev gdal-dev
RUN apk -v cache clean

CMD [ "python" ]

